### ISSUE TITLE
Imported MAGE-TAB overwrites curated IDF in GEOD folder

### ISSUE THREAD

**Issue by anjaf** [ebi-gene-expression-group/geo-importer#9]
Whenever we trigger the GEO importer for bulk RNA-seq experiments, the freshly converted MAGE-TAB file (with name E-GEOD-xxx.idf.txt) gets copied to the $ATLAS_PROD/GEO_import/GEOD/E-GEOD-xxx/ folder where it overwrites the curated E-GEOD-xxx.idf.txt file (if present). 
To prevent this, either change the name of the imported MAGE-TAB (e.g. to E-GEOD-xxx.magetab.txt) or stop the auto copying of this file (only copy the split -idf.txt and -sdrf.txt files).

**Comment by pcm32** [comment]
Ouch! Since when do we reckon that this is happening? Could we recover MAGEtab files from atlas tar archives?

**Comment by anjaf** [comment]
This has been fixed in https://github.com/ebi-gene-expression-group/geo-importer/pull/10 by renaming the files to merged.idf.txt
